class AllPage {

  constructor(page) {
    this.page = page;

    this.controls = {};
    this.controls.createapost = page.locator("#create-a-post-btn");
    this.controls.div = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.padding_scroll_wrapper.top_stiky_filter.ng-tns-c122-2.top-data.ng-star-inserted > feed-toolbar.ng-tns-c122-2 > div.toolbar-container.bg-primary-negative > div.flex-row.justify-flex-end.toolbarContainer-2.ng-star-inserted > div.search-container.flx-align-center.cursor-pointer.hover-search > div.flex-col-center > ng-select.search-input.ng-select-searchable.ng-select-clearable.ng-select.ng-select-single.ng-untouched.ng-pristine.ng-valid > div.ng-select-container > div.ng-value-container > div.ng-input");
    this.controls.input = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.padding_scroll_wrapper.top_stiky_filter.ng-tns-c122-2.top-data.ng-star-inserted > feed-toolbar.ng-tns-c122-2 > div.toolbar-container.bg-primary-negative > div.flex-row.justify-flex-end.toolbarContainer-2.ng-star-inserted > div.search-container.flx-align-center.cursor-pointer.hover-search > div.flex-col-center > ng-select.search-input.ng-select-searchable.ng-select-clearable.ng-select.ng-select-single.ng-untouched.ng-pristine.ng-valid > div.ng-select-container > div.ng-value-container > div.ng-input > input");
    this.controls.habeebaadmin = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.first-post.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > dbx-ds-hover-data.hydrated > a.custom-theme-color");
    this.controls.xaviercooper11 = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.first-post.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > dbx-ds-hover-data.hydrated > a.custom-theme-color");
    this.controls.searchformembers = page.getByPlaceholder("Search for Members");
    this.controls.williamwallace = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > dbx-ds-hover-data.hydrated > a.custom-theme-color");
    this.controls.xaviercooper7 = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > dbx-ds-hover-data.hydrated > a.custom-theme-color");
    this.controls.searchformembers1 = page.getByPlaceholder("Search for Members");
    this.controls.mycompany = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > dbx-ds-hover-data.hydrated > a.custom-theme-color");
    this.controls.xaviercooper2 = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > dbx-ds-hover-data.hydrated > a.custom-theme-color");
    this.controls.automationdepartmenteveryone = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > a.custom-theme-color");
    this.controls.engineeringdepartmenteveryone = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > a.custom-theme-color");
    this.controls.kalel = page.locator("body.ng-tns-0-3 > app-root > landing-page-parent > div.root_parent_container > dbx-ds-layout.sc-dbx-ds-layout-h.hydrated > div.ds-layout-wrapper.sc-dbx-ds-layout.has-left-nav > div.content-wrapper.sc-dbx-ds-layout.sc-dbx-ds-layout-s > home-parent.ng-star-inserted > div.root_parent_container > div.rest_all_content_block > posts-parent.ng-star-inserted > div.full_content_block.sds-bg-neutralGrey-light2 > div.root_posts_layout.take_whole_width_height.flex-col > div.rest_all_content_block > div.full_content_block.page-layout-container > div.root_right_posts_layout.take_whole_width_height.layout-container.layout-item.col-mobile-4.col-tablet-8.col-desktop-12.col-large-desktop-12.hide_scroll_bar.overflow-x-hidden.admin-layout-container > div.flex.w-full.h-auto.layout-item.col-mobile-4.col-tablet-4.pt-4.col-desktop-7.col-large-desktop-7.ng-star-inserted > common-posts-wrapper.w-full.h-auto.ng-star-inserted > all-posts.w-full.h-auto.block > div.rest_all_content_block.all-posts-margin.h-auto.ng-star-inserted > all-posts-list.full_content_block.fit_height.ng-tns-c122-2.ng-star-inserted > div.take_whole_width_height.hide_scroll_bar.ng-tns-c122-2 > div.padding_scroll_wrapper.ng-tns-c122-2 > each-post.ng-tns-c122-2.ng-trigger.ng-trigger-revelSlow.ng-star-inserted > div.post-main-container.ng-star-inserted > div.post-header.flex.justify-between.relative > div.flex > div.flex-col.justify-start.ng-star-inserted > div.user-name.sds-body-m-book > dbx-ds-hover-data.hydrated > a.custom-theme-color");
  }

  /**
   * Get a Playwright Locator by the generated control name.
   * @example page.locator('...') usage: await allPage.locator('createapost').click();
   */
  locator(name) {
    const loc = this.controls[name];
    if (!loc) {
      throw new Error(`Unknown control: ${name}. Known: ${Object.keys(this.controls).join(', ')}`);
    }
    return loc;
  }

  async click(name, options) {
    await this.locator(name).click(options);
  }

  async fill(name, value, options) {
    await this.locator(name).fill(value, options);
  }

  async type(name, value, options) {
    await this.locator(name).type(value, options);
  }

  async text(name) {
    return await this.locator(name).textContent();
  }

  async isVisible(name) {
    return await this.locator(name).isVisible();
  }

}

module.exports = AllPage;
