require('dotenv').config();

const path = require('path');
const express = require('express');
const multer = require('multer');
const JSZip = require('jszip');

const { getConfluenceContentById } = require('../services/confluenceService');
const { extractStructuredRequirements } = require('../agents/prdAgent');
const { generateTestCasesAsArray } = require('../agents/testCaseAgent');
const { generatePlaywright } = require('../agents/playwrightAgent');
const { parseMultiFileOutput } = require('../utils/multiFileWriter');
const { enrichPrdTestsWithVector, toVectorDoc } = require('../vector/prdTestcaseEnrichment');
const { indexTestcase } = require('../vector/testcaseVectorService');
const { closeVectorStore } = require('../vector/vectorStore');
const { getEnv } = require('../utils/env');

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

function parseConfluencePageId(prdLink) {
  const raw = String(prdLink || '').trim();
  if (!raw) return '';
  const fromParam = raw.match(/[?&]pageId=(\d+)/i);
  if (fromParam) return fromParam[1];
  const fromPath = raw.match(/\/pages\/(\d+)/i);
  if (fromPath) return fromPath[1];
  return '';
}

function uniqueBySignature(cases) {
  const map = new Map();
  for (const tc of Array.isArray(cases) ? cases : []) {
    const signature = [
      String(tc?.title || '').trim().toLowerCase(),
      String(tc?.description || '').trim().toLowerCase(),
      String(tc?.steps || '').trim().toLowerCase(),
      String(tc?.expected || '').trim().toLowerCase(),
    ].join('||');
    if (!map.has(signature)) map.set(signature, tc);
  }
  return [...map.values()];
}

app.get('/health', (_req, res) => {
  res.json({ ok: true });
});

app.post('/api/manual-testcases', async (req, res) => {
  const { prdLink, jiraTicket } = req.body || {};
  const pageId = parseConfluencePageId(prdLink);
  if (!pageId) {
    return res.status(400).json({
      error: 'Invalid PRD link. Provide a Confluence link that contains pageId=... or /pages/<id>.',
    });
  }
  if (!jiraTicket || !String(jiraTicket).trim()) {
    return res.status(400).json({ error: 'JIRA ticket is required.' });
  }

  let finalCases = [];
  let upserted = 0;
  try {
    const prdText = await getConfluenceContentById(pageId);
    const structured = await extractStructuredRequirements(prdText);
    const generatedCases = await generateTestCasesAsArray(structured);

    const threshold = Number(getEnv('VECTOR_DUP_THRESHOLD', '0.86'));
    const enriched = await enrichPrdTestsWithVector(generatedCases, { threshold, limit: 5 });
    finalCases = uniqueBySignature(enriched.tests);

    for (let i = 0; i < finalCases.length; i += 1) {
      const doc = toVectorDoc(finalCases[i], i);
      await indexTestcase(doc);
      upserted += 1;
    }
  } catch (error) {
    return res.status(500).json({ error: error.message || 'Manual testcase generation failed.' });
  } finally {
    try {
      await closeVectorStore();
    } catch (_) {
      // ignore cleanup errors
    }
  }

  const fileName = `${String(jiraTicket).trim()}_manual_testcases.json`.replace(/\s+/g, '_');
  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
  res.setHeader('X-Upserted-Count', String(upserted));
  return res.send(JSON.stringify(finalCases, null, 2));
});

app.post('/api/playwright-tests', upload.single('manualTestcaseFile'), async (req, res) => {
  const file = req.file;
  const repoLink = String(req.body?.playwrightRepoLink || '').trim();
  if (!file) {
    return res.status(400).json({ error: 'manualTestcaseFile is required.' });
  }
  if (!repoLink) {
    return res.status(400).json({ error: 'Playwright repo link is required.' });
  }

  try {
    const jsonText = file.buffer.toString('utf8');
    const parsed = JSON.parse(jsonText);
    if (!Array.isArray(parsed)) {
      return res.status(400).json({ error: 'Uploaded manual testcase JSON must be an array.' });
    }

    const generated = await generatePlaywright(parsed);
    const parsedFiles = parseMultiFileOutput(generated);

    const zip = new JSZip();
    zip.file(
      'README.txt',
      [
        'Generated by ai-test-agent web workflow.',
        `Playwright repo link provided: ${repoLink}`,
        '',
        'If output contains multiple files, they are included below.',
      ].join('\n')
    );

    if (parsedFiles.length > 0) {
      for (const f of parsedFiles) {
        zip.file(f.filePath, f.content);
      }
    } else {
      zip.file('generated.spec.js', String(generated || ''));
    }

    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', 'attachment; filename="playwright-tests.zip"');
    return res.send(zipBuffer);
  } catch (error) {
    return res.status(500).json({ error: error.message || 'Playwright generation failed.' });
  }
});

const port = Number(getEnv('WEB_PORT', '3000'));
app.listen(port, () => {
  // eslint-disable-next-line no-console
  console.log(`Web app running at http://localhost:${port}`);
});

